before_script:
  - composer install --no-suggest --no-progress

variables:
  COMPOSER_CACHE_DIR: /cache/composer.cache



unittests:
  stage: test
  image: deriel/laravel:latest
  script:
    - ./check.sh
