before_script:
  - eval `ssh-agent -s`
  - ssh-add <(echo "$SSH_PRIVATE_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  - composer install --no-suggest --no-progress

variables:
  COMPOSER_CACHE_DIR: /cache/composer.cache



unittests:
  stage: test
  image: deriel/laravel:latest
  script:
    - ./check.sh
